[misc] feat: introduce a style bot.
huggingface/diffusers pull request #10274
Opened 2024-12-18 02:18 UTC by sayakpaul

# What does this PR do?

This PR introduces a workflow for allowing us to use the GitHub Actions bot to do `@bot /style` on PRs that are close to merging but cannot be merged because of styling issues. 

I have experimented with the workflow in this dummy repository: https://github.com/sayakpaul/poc-style-bot. 

This is how it'd look like:
<img width="1010" alt="image" src="https://github.com/user-attachments/assets/f2768c15-a446-44a0-b02d-7fc6af86f99c" />

Workflow run: https://github.com/sayakpaul/poc-style-bot/actions/runs/12366322159

@hlky possible for you to give this a look and try it out?

2024-12-18 23:24 UTC, hlky approved these changes
This type of workflow event will only trigger if the workflow is on the default branch so we can't test it here, but it appears correct and is working on your test repo. My only comment is that `make style && make quality` can just be `make style` and sometimes we need to do `ruff check $(check_dirs) setup.py --fix --unsafe-fixes`, probably better to do `--unsafe-fixes` manually though.

https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#issue_comment

> This event will only trigger a workflow run if the workflow file is on the default branch.

2024-12-19 03:01 UTC, sayakpaul commented
> an just be make style and sometimes we need to do ruff check $(check_dirs) setup.py --fix --unsafe-fixes, probably better to do --unsafe-fixes manually though.

Yeah usually `make style && make quality` is the command we're looking into using. Anything other than that, should be applied manually, IMO. 

> This type of workflow event will only trigger if the workflow is on the default branch so we can't test it here

Yeah exactly. Sorry, I should have made it clear. My ask was more about checking the structure of the workflow and the dummy repo I tested it on. 

@DN6 could you give this a look too?

2025-01-06 17:05 UTC, ydshieh commented on .github/workflows/pr_style_bot.yml
> +            git push origin HEAD:${{ steps.pr_info.outputs.headRef }}
Note that this will push to `diffusers/headRef` instead of the original contributor's forked repo'branch (if it is from a forked repository) - If I am not making mistake here.

Better to revise this part I think :-)

2025-01-06 18:02 UTC, ydshieh2 commented on .github/workflows/pr_style_bot.yml
> +            git push origin HEAD:${{ steps.pr_info.outputs.headRef }}
It's because your PR is opened by a branch pushed to the same repository. To actually test the situation, you have to fork the  repository `poc-style-bot` say to (under another github account `sayakapaul_2`), push a branch to `sayakapaul_2/poc-style-bot`, and opening a PR in `sayakpaul/poc-style-bot`.

2025-01-07 10:30 UTC, sayakpaul commented on .github/workflows/pr_style_bot.yml
> +            git push origin HEAD:${{ steps.pr_info.outputs.headRef }}
@ydshieh I pushed some updates to account for your comment here https://github.com/huggingface/diffusers/pull/10274#discussion_r1904410515. LMK.

2025-01-07 10:47 UTC, ydshieh commented on .github/workflows/pr_style_bot.yml
> +            git push origin HEAD:${{ steps.pr_info.outputs.headRef }}
Looks my comment is addressed, although I didn't check line by line.

I always recommend to test it with a `external contributor` (a new github account sayakpaul2) opening a PR from it's forked repo. to your POC repository (under `@sayakpaul`).

But I will leave the final decision to you :-)

2025-01-08 13:19 UTC, hlky commented on .github/workflows/pr_style_bot.yml
> +            git push origin HEAD:${{ steps.pr_info.outputs.headRef }}
Tested with external contributor here https://github.com/sayakpaul/poc-style-bot/pull/2

2025-01-13 16:32 UTC, glegendre01 requested changes

2025-01-13 16:32 UTC, glegendre01 commented on .github/workflows/pr_style_bot.yml
> +          repository: ${{ steps.pr_info.outputs.headRepoFullName }}
```suggestion
          repository: $HEADREPOFULLNAME
```

2025-01-13 16:32 UTC, glegendre01 commented on .github/workflows/pr_style_bot.yml
> +          ref: ${{ steps.pr_info.outputs.headRef }}
```suggestion
          ref: $HEADREF
```

2025-01-13 16:32 UTC, glegendre01 commented on .github/workflows/pr_style_bot.yml
> +        uses: actions/checkout@v3
```suggestion
        uses: actions/checkout@v3
          env: 
          HEADREPOFULLNAME: ${{ steps.pr_info.outputs.headRepoFullName }}
          HEADREF: ${{ steps.pr_info.outputs.headRef }}
```

2025-01-13 16:32 UTC, glegendre01 commented on .github/workflows/pr_style_bot.yml
> +      - name: Debug
can you do the same here ? create 3 env variable and use them on the run

2025-01-13 16:32 UTC, glegendre01 commented on .github/workflows/pr_style_bot.yml
> +          # Should we be comparing the Makefile to check for any differences with `diffusers` main?
yes, i think it's mandatory if the makefile can change on the branch

2025-01-14 08:17 UTC, sayakpaul commented on .github/workflows/pr_style_bot.yml
> +      - name: Debug
Do the latest changes work?

2025-01-14 08:18 UTC, sayakpaul commented on .github/workflows/pr_style_bot.yml
> +          rm -rf main_Makefile
@glegendre01 added this too. LMK if it works for you.

2025-01-14 08:19 UTC, sayakpaul commented on .github/workflows/pr_style_bot.yml
> +            git push origin HEAD:${{ steps.pr_info.outputs.headRef }}
@hlky tested with https://github.com/sayakpaul/poc-style-bot/pull/2.

2025-02-09 04:05 UTC, sayakpaul commented
@glegendre01 a gentle ping.

2025-02-19 14:10 UTC, glegendre01 commented on .github/workflows/pr_style_bot.yml
> +          rm -rf main_Makefile
LGTM

2025-02-19 14:11 UTC, glegendre01 approved these changes

2025-02-19 15:19 UTC, merged

2025-02-19 15:19 UTC, sayakpaul commented
Thanks all for helping :)