[training] add ds support to lora sd3.
huggingface/diffusers pull request #10378
Opened 2024-12-25 10:14 UTC by sayakpaul

# What does this PR do?

Fixes https://github.com/huggingface/diffusers/pull/10252. 

Cc: @leisuzz could you give this a try?

2024-12-25 10:21 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/diffusers/pr_10378). All of your documentation changes will be reflected on that endpoint. The docs are available until 30 days after the last update.

2024-12-30 06:44 UTC, leisuzz commented
@sayakpaul Please take a look at the comment, especially the third comment has to be changed!

2024-12-30 07:48 UTC, sayakpaul commented
> Please take a look at the comment, especially the third comment has to be changed!

No idea what this means.

2024-12-30 09:09 UTC, leisuzz commented
@sayakpaul In the line 1852, I added the modification on `if args.checkpoints_total_limit is not None:`
It should be `if accelerator.is_main_process and args.checkpoints_total_limit is not None:`. Otherwise errors will occur

2024-12-30 09:13 UTC, sayakpaul commented
Can you comment on the changes directly instead? That will be helpful and easier.

2024-12-30 09:37 UTC, leisuzz requested changes

2024-12-30 12:09 UTC, sayakpaul commented on examples/dreambooth/train_dreambooth_lora_sd3.py
> +                    model = unwrap_model(model)
`else` should not be needed as the model would already be type-casted.

2024-12-30 12:10 UTC, sayakpaul commented on examples/dreambooth/train_dreambooth_lora_sd3.py
> +                elif isinstance(unwrap_model(model), type(unwrap_model(text_encoder_one))):  # or text_encoder_two
Addressed

2024-12-30 12:10 UTC, sayakpaul commented on examples/dreambooth/train_dreambooth_lora_sd3.py
> +                    model = unwrap_model(model)
Addressed

2024-12-30 12:34 UTC, linoytsaban reviewed
thanks a lot @leisuzz! LGTM, just a couple of small comments

2024-12-30 12:34 UTC, linoytsaban commented on examples/dreambooth/train_dreambooth_lora_sd3.py
> +                elif isinstance(unwrap_model(model), type(unwrap_model(text_encoder_one))):  # or text_encoder_two
isn't it already be reflected in the models sent to `save_model_hook`?

2024-12-30 12:34 UTC, linoytsaban commented on examples/dreambooth/train_dreambooth_lora_sd3.py
> +                    model = unwrap_model(model)
why is the change of `isinstance(model,...` to `isinstance(unwrap_model(model),...` is needed in the if statement?

2024-12-30 12:46 UTC, sayakpaul commented on examples/dreambooth/train_dreambooth_lora_sd3.py
> +                    model = unwrap_model(model)
That is a deepspeed-specific change as with deepspeed, the model gets wrapped into a `Module`.

2024-12-30 13:05 UTC, linoytsaban commented on examples/dreambooth/train_dreambooth_lora_sd3.py
> +                elif isinstance(unwrap_model(model), type(unwrap_model(text_encoder_one))):  # or text_encoder_two
nvm addressed

2024-12-30 13:06 UTC, linoytsaban approved these changes

2024-12-30 14:01 UTC, merged