pytorch only schedulers
huggingface/diffusers pull request #534
Opened 2022-09-16 15:52 UTC by kashif

Remove numpy clauses from schedulers to make them pytorch only

2022-09-16 15:59 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/diffusers/pr_534). All of your documentation changes will be reflected on that endpoint.

2022-09-23 19:56 UTC, vishnu-anirudh commented on src/diffusers/schedulers/scheduling_ddim.py
> +        self.timesteps = np.arange(0, num_train_timesteps)[::-1]
if we are trying to replace numpy, then this might be better? -->`torch.arange`

2022-09-23 19:57 UTC, vishnu-anirudh commented on src/diffusers/schedulers/scheduling_ddim.py
> +        self.timesteps = (np.arange(0, num_inference_steps) * step_ratio).round()[::-1]
```suggestion
        self.timesteps = (torch.arange(0, num_inference_steps) * step_ratio).round()[::-1]
```

2022-09-23 20:00 UTC, kashif commented
@vishnu-anirudh as far as i am aware the timestep is used for the tqdm counters etc and so there is no need for it to be a torch tensor...

2022-09-23 20:01 UTC, vishnu-anirudh commented on src/diffusers/schedulers/scheduling_ddpm.py
> +        self.timesteps = np.arange(0, num_train_timesteps)[::-1]
```suggestion
        self.timesteps = torch.arange(0, num_train_timesteps)[::-1]
```

2022-09-23 20:11 UTC, vishnu-anirudh requested changes
I put some comments to change from numpy usage to the equivalents one in the pytorch library

2022-09-23 20:11 UTC, vishnu-anirudh commented on src/diffusers/schedulers/scheduling_ddpm.py
>          self.timesteps = np.arange(
```suggestion
        self.timesteps = torch.arange(
```

2022-09-23 20:11 UTC, vishnu-anirudh commented on src/diffusers/schedulers/scheduling_karras_ve.py
>          self.timesteps = np.arange(0, self.num_inference_steps)[::-1].copy()
```suggestion
        self.timesteps = torch.arange(0, self.num_inference_steps)[::-1].copy()
```

2022-09-23 20:11 UTC, vishnu-anirudh commented on src/diffusers/schedulers/scheduling_lms_discrete.py
>          self.timesteps = np.arange(0, num_train_timesteps)[::-1].copy()
```suggestion
        self.timesteps = torch.arange(0, num_train_timesteps)[::-1].copy()
```

2022-09-23 20:11 UTC, vishnu-anirudh commented on src/diffusers/schedulers/scheduling_sde_ve.py
> +        self.discrete_sigmas = torch.exp(torch.linspace(np.log(sigma_min), np.log(sigma_max), num_inference_steps))
```suggestion
        self.discrete_sigmas = torch.exp(torch.linspace(torch.log(sigma_min), torch.log(sigma_max), num_inference_steps))
```

2022-09-23 20:11 UTC, vishnu-anirudh commented on src/diffusers/schedulers/scheduling_sde_vp.py
> +        x = x_mean + diffusion * np.sqrt(-dt) * noise
```suggestion
        x = x_mean + diffusion * torch.sqrt(-dt) * noise
```

2022-09-23 20:11 UTC, vishnu-anirudh commented on tests/test_scheduler.py
> +        assert np.equal(
I think this needs to be reverted if we are moving to pytorch-only code.

2022-09-23 20:11 UTC, vishnu-anirudh commented on tests/test_scheduler.py
> +            np.array([901, 851, 851, 801, 801, 751, 751, 701, 701, 651, 651, 601, 601, 501, 401, 301, 201, 101, 1]),
Same comment as above. I think this needs to be reverted if we are moving to pytorch-only code.

2022-09-23 20:43 UTC, kashif commented
@vishnu-anirudh can you kindly check if i am doing the right thing in the pipelines especially with the `add_noise()` calls thanks!

2022-09-23 21:03 UTC, vishnu-anirudh commented
> @vishnu-anirudh can you kindly check if i am doing the right thing in the pipelines especially with the `add_noise()` calls thanks!

Hello @kashif ,
Thanks for your changes so far. 
I think, in the commit related to the `add_noise`, the type hint seems to be for timestamps ([example](https://github.com/huggingface/diffusers/blob/main/src/diffusers/schedulers/scheduling_lms_discrete.py#L204)).

Though it is a good idea. But it may be good to have consistency in `timesteps` typehint throughout the code.
So if we plan to have `numpy` typehint for other `timesteps`, then it may be better to have `numpy` typehint here (same for torch typehint).

2022-09-25 15:41 UTC, vishnu-anirudh commented on tests/test_scheduler.py
> +        assert np.equal(
Since timesteps need to be nunmpy format, I assume this is necessary. So I'll close this comment.

2022-09-25 15:41 UTC, vishnu-anirudh commented on tests/test_scheduler.py
> +            np.array([901, 851, 851, 801, 801, 751, 751, 701, 701, 651, 651, 601, 601, 501, 401, 301, 201, 101, 1]),
Since `timesteps` need to be in NumPy format, I assume this is necessary. So I'll close this comment.

2022-09-25 15:43 UTC, vishnu-anirudh commented
> > @vishnu-anirudh can you kindly check if i am doing the right thing in the pipelines especially with the `add_noise()` calls thanks!
> 
> Hello @kashif , Thanks for your changes so far. I think, in the commit related to the `add_noise`, the type hint seems to be for timestamps ([example](https://github.com/huggingface/diffusers/blob/main/src/diffusers/schedulers/scheduling_lms_discrete.py#L204)).
> 
> Though it is a good idea. But it may be good to have consistency in `timesteps` typehint throughout the code. So if we plan to have `numpy` typehint for other `timesteps`, then it may be better to have `numpy` typehint here (same for torch typehint).

@kashif, I hope it made sense. Please let me know if that's not what you expected me to check as part of the `add_noise` calls.

2022-09-26 15:00 UTC, anton-l reviewed
I like the changes overall, and the tests are mostly running smoothly, thank you @kashif! 

Getting a device mismatch due to `self.sigmas` always being on `cpu` here: 
```python
>       noisy_samples = original_samples + noise * sigma
E       RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

../src/diffusers/schedulers/scheduling_lms_discrete.py:209: RuntimeError
```
So `scheduler.to(device)` might have to be implemented. But I haven't thought about a solution too much, so maybe you have a workaround.

2022-09-26 15:01 UTC, anton-l commented
@patrickvonplaten @patil-suraj could you give this PR a quick review if you have time? It'll be easier to rebase #637 if this is merged first.

2022-09-26 16:04 UTC, pcuenca commented
> I like the changes overall, and the tests are mostly running smoothly, thank you @kashif!
> 
> Getting a device mismatch due to `self.sigmas` always being on `cpu` here:
> 
> ```python
> >       noisy_samples = original_samples + noise * sigma
> E       RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
> 
> ../src/diffusers/schedulers/scheduling_lms_discrete.py:209: RuntimeError
> ```
> 
> So `scheduler.to(device)` might have to be implemented. But I haven't thought about a solution too much, so maybe you have a workaround.

We already have a move immediately before: https://github.com/huggingface/diffusers/blob/2cb7a3373e9b4f8a78bc277b65b86a24804675f2/src/diffusers/schedulers/scheduling_lms_discrete.py#L203

I would suggest something like this in this case:

```Python
sigmas = self.sigmas.to(original_samples.device)
timesteps = timesteps.to(original_samples.device)
```

Unless we want to do computation in CPU as I think we do in the other schedulers.

2022-09-26 17:35 UTC, kashif commented
@pcuenca fixed

2022-09-27 12:37 UTC, patrickvonplaten commented on src/diffusers/pipelines/ddpm/pipeline_ddpm.py
> -        scheduler = scheduler.set_format("pt")
nice!

2022-09-27 12:56 UTC, patrickvonplaten approved these changes
Once tests are green, let's merge this one as it's quite important :-)

2022-09-27 12:59 UTC, patrickvonplaten commented on src/diffusers/schedulers/scheduling_pndm.py
> +        self.alphas_cumprod
```suggestion
```

2022-09-27 13:12 UTC, vishnu-anirudh approved these changes

2022-09-27 13:27 UTC, anton-l commented
Great work @kashif!

2022-09-27 13:27 UTC, merged