chore: fix typos
huggingface/diffusers pull request #5386
Opened 2023-10-13 14:39 UTC by afuetterer

# What does this PR do?

Hi, this is my first PR to the project. It fixes some minor typos.

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [ ] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

2023-10-15 07:52 UTC, psychedelicious requested changes

2023-10-15 07:52 UTC, psychedelicious commented on src/diffusers/pipelines/shap_e/renderer.py
> +        # 1. project the paramters from the generated latents
```suggestion
        # 1. project the parameters from the generated latents
```

2023-10-15 09:06 UTC, afuetterer commented on src/diffusers/pipelines/shap_e/renderer.py
> +        # 1. project the paramters from the generated latents
Of course, I missed that one.

2023-10-15 09:06 UTC, afuetterer commented
Please feel free to squash, if you merge.

2023-10-16 13:13 UTC, patrickvonplaten approved these changes
Thanks a bunch!

2023-10-16 13:21 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/diffusers/pr_5386). All of your documentation changes will be reflected on that endpoint.

2023-10-16 13:23 UTC, merged