SD 1.5 Support For Advanced Lora Training (train_dreambooth_lora_sdxl_advanced.py)
huggingface/diffusers pull request #6449
Opened 2024-01-04 06:05 UTC by brandostrong

A quick adaptation to support people interested in using this method on 1.5 models.

# What does this PR do?

Adds support for 1.5 models on the advanced dreambooth training method laid out by @linoytsaban 

## Who can review?

@linoytsaban @sayakpaul

2024-01-04 06:12 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/diffusers/pr_6449). All of your documentation changes will be reflected on that endpoint. The docs are available until 30 days after the last update.

2024-01-04 10:12 UTC, linoytsaban requested changes
Thanks for the PR! looks great, excited to see what LoRAs will come out of the advanced script with SD!

I left a few comments regarding compatibility issues for the prompt text encoding, and unit added conditions. I think all should be quite quick to fix if you don't mind taking another look 😊
[examples/dreambooth/train_dreambooth_lora.py](https://github.com/huggingface/diffusers/blob/main/examples/dreambooth/train_dreambooth_lora.py)  - this might help with making those adjustments :)

2024-01-04 10:25 UTC, brandostrong commented
Thank you so much for the comments Linoy! I appreciate how much detail you just provided me. Admittedly, this was something I quickly put together since I saw a demand for 1.5. It's rather late right now, so when I find time tomorrow I'll make the necessary changes.

Also, did you happen to test your script at all on 1.5, and do you have any comments on the efficacy of it?

2024-01-04 10:44 UTC, linoytsaban commented
Awesome thanks so much😁
admittedly I only tried the advanced features with sdxl, so I'm intrigued!

2024-01-04 23:57 UTC, brandostrong commented
I've made the suggested changes, and it runs but I'm not sure if it's training correctly. There seems to be some fundamental differences(at least in naming, this is a bit over my head) between the base sdxl and 1.5 training scripts, and in the case of encode_prompt we have fairly different parameters and arguments.  Could you give it a look? Is there an example dataset and **full** list of parameters that can be shared and compared as well?

2024-01-05 11:46 UTC, linoytsaban commented
Thanks a lot! 

> There seems to be some fundamental differences(at least in naming, this is a bit over my head) between the base sdxl and 1.5 training scripts, but despite this it seems to work. Could you give it a test as well?

Sure! I'll go over it and run some experiments :)

2024-01-07 22:53 UTC, brandostrong commented
Hi, I've spent the last few days testing and it holds up against my similar training in kohya. Both styles and likenesses are successful, though it really excels at styles.

2024-01-08 01:21 UTC, sayakpaul commented
Thanks so much for your work!

Could we see some results? Also, let's get the code quality fixed, so that we can merge :)

2024-01-22 00:17 UTC, brandostrong commented
Here are some results, I've attached the embedding and lora of a style(and somewhat character) train. 
I would say it trains just fine :)

[offscriptstyleadv.zip](https://github.com/huggingface/diffusers/files/14003279/offscriptstyleadv.zip)
The instance prompt is "in the style of offscriptstyle"

And attached are some example images from comfyui and wandb:
![NVIDIA_Share_MrarE8lvp1](https://github.com/huggingface/diffusers/assets/2181431/50af0882-23e9-4e8a-8f4b-6355f670005c)
![NVIDIA_Share_m5PQrQRVTq](https://github.com/huggingface/diffusers/assets/2181431/14f14be6-c4d3-465a-ad2f-95cac80475be)
![image](https://github.com/huggingface/diffusers/assets/2181431/c768699a-8e5c-437f-a8bb-97d79784ad09)

2024-01-22 01:19 UTC, sayakpaul commented
Cc: @linoytsaban

2024-01-22 08:33 UTC, linoytsaban commented
Looks good @brandostrong! if you don't mind taking a look and merge my 2 suggestions (bug fixes for checkpoint saving) I think we'd be good to go 😁

2024-01-22 08:36 UTC, linoytsaban commented
> Here are some results training a 2d style off the base sd 1.5 checkpoint, I've attached the embedding and lora of a style(and somewhat character) train. I would say it trains just fine :). @sayakpaul @linoytsaban , thanks for the help, hopefully this meets the quality requirements.
> 
> [offscriptstyleadv.zip](https://github.com/huggingface/diffusers/files/14003279/offscriptstyleadv.zip) The instance prompt is "in the style of offscriptstyle"
> 
> And attached are some example images from comfyui and wandb: ![NVIDIA_Share_MrarE8lvp1](https://private-user-images.githubusercontent.com/2181431/298424638-50af0882-23e9-4e8a-8f4b-6355f670005c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MTI3NDQsIm5iZiI6MTcwNTkxMjQ0NCwicGF0aCI6Ii8yMTgxNDMxLzI5ODQyNDYzOC01MGFmMDg4Mi0yM2U5LTRlOGEtOGY0Yi02MzU1ZjY3MDAwNWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjJUMDgzNDA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDBkYmE4NmUwMmI1YTE0YTkwMDgxZjgzNTAxYWVjNjFiNWIyZTZmNmY0NDBhMTIwYjg5MGI1ZmYzMWYyYTdjZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.c1MYqsXM9izXjtV9zSWal3REFHwpIPZz7OUUtjG-mnc) ![NVIDIA_Share_m5PQrQRVTq](https://private-user-images.githubusercontent.com/2181431/298424639-14f14be6-c4d3-465a-ad2f-95cac80475be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MTI3NDQsIm5iZiI6MTcwNTkxMjQ0NCwicGF0aCI6Ii8yMTgxNDMxLzI5ODQyNDYzOS0xNGYxNGJlNi1jNGQzLTQ2NWEtYWQyZi05NWNhYzgwNDc1YmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjJUMDgzNDA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGRhOTBlMzZiNDk3OTJiZDNlNzMxMDE5MTAwMzA0NzMzM2RhOTRlOTc3YTM4Y2EwMmEyZmZjMzhkZTkzNzBmNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Dd095Z1Qm5pAOqbz5iSY0WPzvQ7YBd410oUyY3H-CkY) ![image](https://private-user-images.githubusercontent.com/2181431/298424769-c768699a-8e5c-437f-a8bb-97d79784ad09.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MTI3NDQsIm5iZiI6MTcwNTkxMjQ0NCwicGF0aCI6Ii8yMTgxNDMxLzI5ODQyNDc2OS1jNzY4Njk5YS04ZTVjLTQzN2YtYThiYi05N2Q3OTc4NGFkMDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjJUMDgzNDA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmFlMzhhYWFhMDVkOGM4ODk5OWViMmI5NGI4YjE3ZWQzNmNmNTQwODBjMTFkN2YyMGI1YzBiM2E0ZjVkYWFjOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jCZT7X5BhIL--X0H0RnZ_pJhGfQeKCTpQztCmb4zV3s)

btw @brandostrong - did you try prompting "in the style of `<s0><s1>` offscriptstyle"? Just curious because that way we also leverage the new optimized embeddings which should improve results even more :)

2024-01-22 18:31 UTC, brandostrong commented
Ah oops, the entire essence of this training workflow, totally forgot. I'll send screenshots in an hour or so with the same seed/prompt. I'm running a long animatediff so my VRAM is currently parked at max

2024-01-22 18:34 UTC, brandostrong commented
> Looks good @brandostrong! if you don't mind taking a look and merge my 2 suggestions (bug fixes for checkpoint saving) I think we'd be good to go 😁

Was the merge I just made the suggestions? I'm not that experienced with much more than solo git.

2024-01-22 18:36 UTC, linoytsaban commented
> Ah oops, the entire essence of this training workflow, totally forgot. I'll send screenshots in an hour or so with the same seed/prompt. I'm running a long animatediff so my VRAM is currently parked at max

no worries! 😁

2024-01-22 18:44 UTC, linoytsaban commented
> > Looks good @brandostrong! if you don't mind taking a look and merge my 2 suggestions (bug fixes for checkpoint saving) I think we'd be good to go 😁
> 
> Was the merge I just made the suggestions? I'm not that experienced with much more than solo git.

I believe they were not merged yet :) can you see my new comments? I think that would do it 😊

2024-01-23 12:09 UTC, linoytsaban approved these changes

2024-01-23 12:09 UTC, linoytsaban commented on examples/advanced_diffusion_training/train_dreambooth_lora_sd15_advanced.py
> +            )
```suggestion
            StableDiffusionPipeline.save_lora_weights(
                output_dir,
                unet_lora_layers=unet_lora_layers_to_save,
                text_encoder_lora_layers=text_encoder_one_lora_layers_to_save,
            )
        if args.train_text_encoder_ti:
            embedding_handler.save_embeddings(f"{output_dir}/{args.output_dir}_emb.safetensors")
```

2024-01-23 12:09 UTC, linoytsaban commented on examples/advanced_diffusion_training/train_dreambooth_lora_sd15_advanced.py
> +                else:
```suggestion
                elif isinstance(model, type(accelerator.unwrap_model(text_encoder_one))):
                    if args.train_text_encoder:
                        text_encoder_one_lora_layers_to_save = convert_state_dict_to_diffusers(
                            get_peft_model_state_dict(model)
                        )
```

2024-01-23 12:09 UTC, linoytsaban commented on examples/advanced_diffusion_training/train_dreambooth_lora_sd15_advanced.py
> +                else:
makes sure we save checkpoints correctly, as per bug fix in https://github.com/huggingface/diffusers/pull/6464

2024-01-23 12:09 UTC, linoytsaban commented on examples/advanced_diffusion_training/train_dreambooth_lora_sd15_advanced.py
> +            )
makes sure we save checkpoints correctly, as per bug fix in https://github.com/huggingface/diffusers/pull/6464

2024-01-23 12:18 UTC, linoytsaban commented
@brandostrong I just committed 2 minor changes to `save_model_hook` - makes sure we save checkpoints correctly, as per the bug fix in #6464. I think we can ship now 😁🛳️

2024-01-23 20:00 UTC, brandostrong reviewed
Awesome, thank you :D

2024-01-24 09:20 UTC, merged