[LoRA] Remove legacy LoRA code and related adjustments
huggingface/diffusers pull request #8316
Opened 2024-05-30 07:46 UTC by sayakpaul

# What does this PR do?

It's been a while since we have had legacy LoRA code, and we have no reason to continue to include them within the library, given that `peft` is a required dependency for all things LoRA within the library. 

This PR removes all the legacy code from `loaders/lora.py` and `loaders/unet.py` and revises the `load_attn_procs()` method in the UNet. 

Additionally, I have run all the slow LoRA tests to ensure they're passing. 

In summary, this PR should make our LoRA-related code blocks much cleaner and easier to navigate through.

2024-05-30 07:47 UTC, sayakpaul commented
Requesting for reviews from @younesbelkada and @BenjaminBossan initially. Once done, will ping others from the team.

2024-05-30 07:47 UTC, sayakpaul commented on .github/workflows/pr_test_peft_backend.yml
> +        path: reports
We should upload the test reports for LoRA.

2024-05-30 07:49 UTC, sayakpaul commented on src/diffusers/loaders/lora.py
> -        cls, state_dict, network_alphas, transformer, low_cpu_mem_usage=None, adapter_name=None, _pipeline=None
We have absolutely no reason to continue to include `low_cpu_mem_usage` when using `peft`.

2024-05-30 07:49 UTC, sayakpaul commented on src/diffusers/loaders/lora.py
> -        low_cpu_mem_usage = low_cpu_mem_usage if low_cpu_mem_usage is not None else _LOW_CPU_MEM_USAGE_DEFAULT
`low_cpu_mem_usage` isn't used when using `peft`.

2024-05-30 07:49 UTC, sayakpaul commented on src/diffusers/loaders/lora.py
> -                    module.set_lora_layer(None)
Legacy code. Shouldn't stay.

2024-05-30 07:50 UTC, sayakpaul commented on src/diffusers/loaders/unet.py
> -            state_dict, network_alphas = self.convert_state_dict_legacy_attn_format(state_dict, network_alphas)
No need as already handled in `peft` and the backend.

2024-05-30 07:50 UTC, sayakpaul commented on src/diffusers/loaders/unet.py
> +            )
`_process_lora()` injects the LoRA state dict inline.

2024-05-30 07:52 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/diffusers/pr_8316). All of your documentation changes will be reflected on that endpoint. The docs are available until 30 days after the last update.

2024-05-30 11:00 UTC, BenjaminBossan requested changes
Thanks a lot for taking care of removing the legacy LoRA code. Always nice to see more code being removed than added: +388 −425

Overall, this LGTM, from my understanding, most changes are about removing the legacy code paths and moving some LoRA-related code around without actually changing the logic. The tests all passing is the best indicator that nothing was broken.

To me, it is unclear if the removal of the `low_cpu_mem_usage` and `mirror` options are in any way related to the refactor. If not, maybe in the future it would be better to split these types of PRs to make them easier to review.

2024-05-30 13:38 UTC, sayakpaul commented on src/diffusers/loaders/unet.py
> +    def _process_lora(self, state_dict, unet_identifier_key, network_alphas, adapter_name, _pipeline):
See if it makes sense now.

2024-05-30 13:41 UTC, sayakpaul commented
@BenjaminBossan thanks for the comments. I have addressed all of them or have replied to them. 

> To me, it is unclear if the removal of the low_cpu_mem_usage and mirror options are in any way related to the refactor. If not, maybe in the future it would be better to split these types of PRs to make them easier to review.

I fully agree with you here. I don't like increasing the scope of PR review, either. However, I decided to include the changes related to `low_cpu_mem_usage` because it's actually not used in the peft part of the code. So, I thought it's related. 

LMK if it makes sense.

2024-06-04 10:00 UTC, BenjaminBossan approved these changes
Sorry, I forgot to reply to your reply. Thanks for making the adjustments and again big thanks for taking care of the legacy code :rocket:

2024-06-04 12:57 UTC, sayakpaul commented
@yiyixuxu ready for a review now that I have an approval from Benjamin.

2024-06-05 01:51 UTC, yiyixuxu approved these changes
ok to merge because all the tests passed and @BenjaminBossan approved!

2024-06-05 04:15 UTC, merged