support brushnet (BrushNet: A Plug-and-Play Image Inpainting Model with Decomposed Dual-Branch Diffusion)
huggingface/diffusers pull request #9125
Opened 2024-08-08 03:14 UTC by juxuan27

# What does this PR do?

This PR is to support [BrushNet](https://github.com/TencentARC/BrushNet) (BrushNet: A Plug-and-Play Image Inpainting Model with Decomposed Dual-Branch Diffusion) in diffusers. It is a plug-and-play inpainting method that have been accepted to ECCV2024.

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [x] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [x] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

2024-08-08 05:22 UTC, cs-mshah commented on examples/brushnet/train_brushnet.py
> +    BrushNetModel,
We need to add the model classes as well.

2024-08-08 05:24 UTC, cs-mshah requested changes
We need to add the `BrushNetModel` and `StableDiffusionBrushNetPipeline` to diffusers as well.

2024-08-08 05:31 UTC, cs-mshah commented
Would it be a better idea  to decouple the code and keep it only to the `examples` folder as done by https://github.com/attashe/BrushNetSimple

2024-08-08 05:37 UTC, juxuan27 commented
I am working on this! Sorry for forgetting to add the `BrushNetModel` and `StableDiffusionBrushNetPipeline`. I will pin you once I finished. Thanks for your review.

2024-08-19 00:29 UTC, yiyixuxu commented
I think this should either go into the community folder (https://github.com/huggingface/diffusers/tree/main/examples/community) as a community pipeline, or research_projects folder (https://github.com/huggingface/diffusers/tree/main/examples/research_projects) , no?

2024-09-05 23:49 UTC, closed without merging