Kolors diffdiff
huggingface/diffusers pull request #9423
Opened 2024-09-12 06:22 UTC by saqlain2204

# What does this PR do?

Adds [Differential Diffusion](https://arxiv.org/abs/2306.00950) to Kolors

Fixes Partially https://github.com/huggingface/diffusers/issues/8924(Kolors)

2024-09-12 06:24 UTC, saqlain2204 commented
I am not able to lead kolors in colab free tier. Tried to resolve it by using memory optimizations, but it dint work. Am I going wrong somewhere?

2024-09-12 07:44 UTC, a-r-r-o-w commented
Thanks for working on this! For Kolors, I think @asomoza might be able to share some suggestions on how to save memory and minimal VRAM requirements as he worked on it. If it doesn't work on a free-tier colab, I'll try and test the PR :)

2024-09-12 08:30 UTC, saqlain2204 commented
Sure. Thanks :)

2024-10-07 07:38 UTC, asomoza commented
Hi @saqlain2204 sorry I missed this for so long. Kolors uses a big text encoder and a custom one that isn't in transformers yet so we can't optimize it for now, so for the time being, we can't use a quantized version of it.

As I remember the text encoder is around 10GB and the unet 6 GB so they won't fit in the free tier colab GPU, don't remember how much RAM it has to store them in the CPU, but it should work with `enable_model_cpu_offload`. There was a problem before where the VRAM wasn't getting freed but that was fixed a while ago, maybe you can try again.

If it doesn't work like this, sadly we won't be able to optimize it just yet so it can run on the free tier colab.

2024-10-09 01:52 UTC, yiyixuxu commented
should we merge this?

2024-10-09 03:29 UTC, saqlain2204 commented
Hi @asomoza ,
Thanks for the suggestions. Will try running it by making the above changes and update it here.

2024-10-09 16:11 UTC, asomoza commented
@saqlain2204 can you update the description with the typical examples with use for diff-diff, you can get them from the [SD3](https://github.com/huggingface/diffusers/pull/8679) implementation.

This way you and we can make sure it works which is pretty much the only requirement for community pipelines. From a quick look, it seems you're missing the map/mask input so there's no way to pass the depthmap/mask to the pipeline call method.

2024-10-09 18:56 UTC, saqlain2204 commented
I have updated. Can you please review it.

2024-10-10 01:33 UTC, asomoza requested changes
we need a couple of fixes, the rest looks good

2024-10-10 01:33 UTC, asomoza commented on examples/community/pipeline_kolors_differential_img2img.py
> +            )
```suggestion
        if latents is None:
            latents = self.prepare_latents(
                init_image,
                latent_timestep,
                batch_size,
                num_images_per_prompt,
                prompt_embeds.dtype,
                device,
                generator,
                add_noise,
            )
```

2024-10-10 01:33 UTC, asomoza commented on examples/community/pipeline_kolors_differential_img2img.py
> +        )
```suggestion
        original_with_noise = self.prepare_latents(
            init_image, timesteps, batch_size, num_images_per_prompt, prompt_embeds.dtype, device, generator
        )
```

2024-10-10 12:38 UTC, asomoza commented
@saqlain2204 can you please run `make style` and `make quality`

2024-10-11 13:47 UTC, asomoza commented
thanks!

2024-10-11 13:47 UTC, merged

2024-10-11 13:48 UTC, saqlain2204 commented
👍

2024-10-11 13:53 UTC, saqlain2204 commented
Thanks @a-r-r-o-w @asomoza !